### ISSUE TITLE
Restore a classifier

### ISSUE THREAD

**Issue by haganbt** [miguelmota/bayes-classifier#1]
Is there any way to restore a classifier? For example, I would like to save the classifier object to a DB and then update that as new training data is received.

I cannot see any way to restore the data which means that the classifier cannot be persisted and reloaded.

Note Natural has a ```restore``` function. See [here](https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/classifier.js#L392).

Appreciate any thoughts.

**Comment by miguelmota** [comment]
Fixed in https://github.com/miguelmota/bayes-classifier/pull/2
